### ISSUE TITLE
Add support ofr mc:Ignorable whe use xaml activities

### ISSUE THREAD

**Issue by danielmeza** [UiPath/CoreWF#105]
Add support for mc:Ignorable whe I try to run a xaml activity generated by the designer its throw and exception when I run it :

`System.Xaml.XamlObjectWriterException
  HResult=0x80131500
  Message='Cannot set unknown member '{http://schemas.microsoft.com/netfx/2010/xaml/activities/debugger}DebugSymbol.Symbol'.' Line number '52' and line position '8'.
  Source=System.Xaml
  StackTrace:
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)
   at System.Activities.XamlIntegration.FuncFactory`1.Evaluate()
   at System.Activities.Activity.OnInternalCacheMetadata(Boolean createEmptyBindings)
   at System.Activities.Activity.InternalCacheMetadata(Boolean createEmptyBindings, IList`1& validationErrors)
   at System.Activities.ActivityUtilities.ProcessActivity(ChildActivity childActivity, ChildActivity& nextActivity, Stack`1& activitiesRemaining, ActivityCallStack parentChain, IList`1& validationErrors, ProcessActivityTreeOptions options, ProcessActivityCallback callback)
   at System.Activities.ActivityUtilities.ProcessActivityTreeCore(ChildActivity currentActivity, ActivityCallStack parentChain, ProcessActivityTreeOptions options, ProcessActivityCallback callback, IList`1& validationErrors)
   at System.Activities.ActivityUtilities.CacheRootMetadata(Activity activity, LocationReferenceEnvironment hostEnvironment, ProcessActivityTreeOptions options, ProcessActivityCallback callback, IList`1& validationErrors)
   at System.Activities.Hosting.WorkflowInstance.ValidateWorkflow(WorkflowInstanceExtensionManager extensionManager)
   at System.Activities.Hosting.WorkflowInstance.RegisterExtensionManager(WorkflowInstanceExtensionManager extensionManager)
   at System.Activities.WorkflowApplication.EnsureInitialized()
   at System.Activities.WorkflowApplication.RunInstance(WorkflowApplication instance)
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow)
   at WorkflowApp.Program.Main(String[] args) in C:\Users\DMeza\source\repos\WoflowPort\WorkflowApp\Program.cs:line 25
`

``` xaml
<Activity mc:Ignorable="sap sap2010 sads" x:Class="WorkflowApp.Workflow1"
 xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities"
 xmlns:local="clr-namespace:WorkflowApp"
 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
 xmlns:mca="clr-namespace:Microsoft.CSharp.Activities;assembly=UiPath.Workflow"
 xmlns:s="clr-namespace:System;assembly=mscorlib"
 xmlns:sads="http://schemas.microsoft.com/netfx/2010/xaml/activities/debugger"
 xmlns:sap="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation"
 xmlns:sap2010="http://schemas.microsoft.com/netfx/2010/xaml/activities/presentation"
 xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib"
 xmlns:sco="clr-namespace:System.Collections.ObjectModel;assembly=mscorlib"
 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <x:Members>
    <x:Property Name="Items" Type="InArgument(s:Object[])" />
  </x:Members>
  <sap2010:ExpressionActivityEditor.ExpressionActivityEditor>C#</sap2010:ExpressionActivityEditor.ExpressionActivityEditor>
  <sap2010:WorkflowViewState.IdRef>WorkflowApp.Workflow1_1</sap2010:WorkflowViewState.IdRef>
  <TextExpression.NamespacesForImplementation>
    <sco:Collection x:TypeArguments="x:String">
      <x:String>System</x:String>
      <x:String>System.Collections.Generic</x:String>
      <x:String>System.Data</x:String>
      <x:String>System.Linq</x:String>
      <x:String>System.Text</x:String>
    </sco:Collection>
  </TextExpression.NamespacesForImplementation>
  <TextExpression.ReferencesForImplementation>
    <sco:Collection x:TypeArguments="AssemblyReference">
      <AssemblyReference>Microsoft.CSharp</AssemblyReference>
      <AssemblyReference>System</AssemblyReference>
      <AssemblyReference>System.Activities</AssemblyReference>
      <AssemblyReference>System.Core</AssemblyReference>
      <AssemblyReference>System.Data</AssemblyReference>
      <AssemblyReference>System.Runtime.Serialization</AssemblyReference>
      <AssemblyReference>System.ServiceModel</AssemblyReference>
      <AssemblyReference>System.ServiceModel.Activities</AssemblyReference>
      <AssemblyReference>System.Xaml</AssemblyReference>
      <AssemblyReference>System.Xml</AssemblyReference>
      <AssemblyReference>System.Xml.Linq</AssemblyReference>
      <AssemblyReference>PresentationFramework</AssemblyReference>
      <AssemblyReference>PresentationCore</AssemblyReference>
      <AssemblyReference>System.Activities.Presentation</AssemblyReference>
      <AssemblyReference>WindowsBase</AssemblyReference>
      <AssemblyReference>mscorlib</AssemblyReference>
      <AssemblyReference>WorkflowApp</AssemblyReference>
    </sco:Collection>
  </TextExpression.ReferencesForImplementation>
  <local:CustomForeach sap2010:ExpressionActivityEditor.ExpressionActivityEditor="C#" sap2010:WorkflowViewState.IdRef="WorkflowApp.CustomForeach_1">
    <local:CustomForeach.Body>
      <ActivityAction x:TypeArguments="x:Object">
        <ActivityAction.Argument>
          <DelegateInArgument x:TypeArguments="x:Object" Name="Argument" />
        </ActivityAction.Argument>
        <WriteLine sap2010:WorkflowViewState.IdRef="WriteLine_1">
          <InArgument x:TypeArguments="x:String">
            <mca:CSharpValue x:TypeArguments="x:String">Argument.ToString()</mca:CSharpValue>
          </InArgument>
        </WriteLine>
      </ActivityAction>
    </local:CustomForeach.Body>
    <local:CustomForeach.Items>
      <InArgument x:TypeArguments="s:Object[]">
        <mca:CSharpValue x:TypeArguments="s:Object[]">Items</mca:CSharpValue>
      </InArgument>
    </local:CustomForeach.Items>
    <sap2010:WorkflowViewState.ViewStateManager>
      <sap2010:ViewStateManager>
        <sap2010:ViewStateData Id="InvokeDelegate_1" sap2010:WorkflowViewState.IdRef="ViewStateData_1" />
        <sap2010:ViewStateData Id="Assign_1" sap2010:WorkflowViewState.IdRef="ViewStateData_2" />
        <sap2010:ViewStateData Id="Sequence_1" sap2010:WorkflowViewState.IdRef="ViewStateData_3" />
        <sap2010:ViewStateData Id="While_1" sap2010:WorkflowViewState.IdRef="ViewStateData_4" />
        <sap2010:ViewStateData Id="WorkflowApp.CustomForeach_1" sap2010:WorkflowViewState.IdRef="ViewStateData_5" />
      </sap2010:ViewStateManager>
    </sap2010:WorkflowViewState.ViewStateManager>
    <sads:DebugSymbol.Symbol>d0FDOlxVc2Vyc1xETWV6YVxzb3VyY2VccmVwb3NcV29mbG93UG9ydFxXb3JrZmxvd0FwcFxXb3JrZmxvdzEueGFtbAQwA0wZAgEBPwk/TgIBBjYJOhUCAQI4DTheAgED</sads:DebugSymbol.Symbol>
  </local:CustomForeach>
  <sap2010:WorkflowViewState.ViewStateManager>
    <sap2010:ViewStateManager>
      <sap2010:ViewStateData Id="WriteLine_1" sap:VirtualizedContainerService.HintSize="210,62" />
      <sap2010:ViewStateData Id="ViewStateData_1" sap:VirtualizedContainerService.HintSize="242,67" />
      <sap2010:ViewStateData Id="ViewStateData_2" sap:VirtualizedContainerService.HintSize="242,62" />
      <sap2010:ViewStateData Id="ViewStateData_3" sap:VirtualizedContainerService.HintSize="264,293">
        <sap:WorkflowViewStateService.ViewState>
          <scg:Dictionary x:TypeArguments="x:String, x:Object">
            <x:Boolean x:Key="IsExpanded">True</x:Boolean>
          </scg:Dictionary>
        </sap:WorkflowViewStateService.ViewState>
      </sap2010:ViewStateData>
      <sap2010:ViewStateData Id="ViewStateData_4" sap:VirtualizedContainerService.HintSize="464,453" />
      <sap2010:ViewStateData Id="ViewStateData_5" sap:VirtualizedContainerService.HintSize="504,300" />
      <sap2010:ViewStateData Id="WorkflowApp.CustomForeach_1" sap:VirtualizedContainerService.HintSize="284,192" />
      <sap2010:ViewStateData Id="WorkflowApp.Workflow1_1" sap:VirtualizedContainerService.HintSize="324,272" />
    </sap2010:ViewStateManager>
  </sap2010:WorkflowViewState.ViewStateManager>
</Activity>
```
The error is cauded by `<sads:DebugSymbol.Symbol>d0FDOlxVc2Vyc1xETWV6YVxzb3VyY2VccmVwb3NcV29mbG93UG9ydFxXb3JrZmxvd0FwcFxXb3JrZmxvdzEueGFtbAQwA0wZAgEBPwk/TgIBBjYJOhUCAQI4DTheAgED</sads:DebugSymbol.Symbol>` line but this line should be ignored cause is in the mc:Ingorable clause

**Comment by danielmeza** [comment]
This nos a issue, I was loading the .g.xaml file instead of the original .xaml file
