### ISSUE TITLE
DynamicActivity

### ISSUE THREAD

**Issue by ewinnington** [UiPath/CoreWF#3]
Will DynamicActivity be ported to CoreWF? Or is the functionality covered in some other way?

This would allow "To create an activity at runtime using imperative code" as described in the upper part of https://msdn.microsoft.com/en-us/library/ee358722(v=vs.110).aspx

**Comment by dmetzgar** [comment]
DynamicActivity takes a heavy dependency on System.ComponentModel, most of which is not ported to Core. There are some parts of componentmodel, but not enough to cover WF scenarios. It would have to be evaluated to see if regular reflection could be used instead.

**Comment by dmetzgar** [comment]
Looks like .NET Standard 2.0 is planning to have PropertyDescriptor and TypeDescriptor. Those are key for porting dynamicactivity and automatic cachemetadata.

**Comment by ewinnington** [comment]
With 2.0 arriving soon, is there something external contributors could do to help port coreWF?

**Comment by dmetzgar** [comment]
I updated the readme with a bit more details. Would you mind having a look?

**Comment by ewinnington** [comment]
Thanks for the update. So if I understand correctly, we can fork your repo and start bringing in the DynamicActivity and the ActivityXamlServices from the MIT licensed [ReferenceSource](https://github.com/Microsoft/referencesource), get that to compile with NetStandard 2.0, add [PortableXAML](https://github.com/cwensley/Portable.Xaml) for the parsing and we are off to the races?

Thank you again for that update.

**Comment by dmetzgar** [comment]
Yes, that's right! I'll be helping out here and there but all of this work is definitely up for grabs.

**Comment by ewinnington** [comment]
I've started going through adding DynamicActivity and re-enabling attributes such as [Ambient] through pulling in PortableXAML. 

Was there any documentation or porting information in the move to net core? 
A list of the remappping of the namespaces perhaps? Microsoft.Activities to CoreWf. 

I'll diff with the reference source to try and understand the changes.

**Comment by ewinnington** [comment]
I've brought DynamicActivity without any XAML namespace into coreWF. It compiles, but does not work for the simple example of ["To create an activity at runtime using imperative code" ](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/creating-an-activity-at-runtime-with-dynamicactivity). 

I'm getting this exception: 

Unhandled Exception: CoreWf.InvalidWorkflowException: The following errors were encountered while processing the workflow tree:
'DynamicActivity': The private implementation of activity '1: DynamicActivity' has the following validation error:   An error occurred while attempting to extract the target object of type 'CoreWf.InArgument`1[System.String]' from the method call expression 'value(DynamicConsoleApp.DynamicDemo+<>c__DisplayClass0_0).textOut.Get(env)'.  Note that the expression determining the object of type 'CoreWf.InArgument`1[System.String]' must not require the runtime context.  Error: The sub-expression for the object of type 'CoreWf.InArgument`1[System.String]' resulted in a location reference that is not visible at this scope.
   at CoreWf.Validation.ActivityValidationServices.ThrowIfViolationsExist(IList`1 validationErrors, ExceptionReason reason) in corewf\src\CoreWf\Validation\ActivityValidationServices.cs:line 64
   at CoreWf.Hosting.WorkflowInstance.ValidateWorkflow(WorkflowInstanceExtensionManager extensionManager) in corewf\src\CoreWf\Hosting\WorkflowInstance.cs:line 359
   at CoreWf.Hosting.WorkflowInstance.RegisterExtensionManager(WorkflowInstanceExtensionManager extensionManager) in corewf\src\CoreWf\Hosting\WorkflowInstance.cs:line 184
   at CoreWf.WorkflowApplication.EnsureInitialized() in corewf\src\CoreWf\WorkflowApplication.cs:line 615
   at CoreWf.WorkflowApplication.RunInstance(WorkflowApplication instance) in corewf\src\CoreWf\WorkflowApplication.cs:line 1220
   at CoreWf.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout) in corewf\src\CoreWf\WorkflowApplication.cs:line 1250
   at CoreWf.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions) in corewf\src\CoreWf\WorkflowInvoker.cs:line 331
   at CoreWf.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs) in corewf\src\CoreWf\WorkflowInvoker.cs:line 97
   at DynamicConsoleApp.DynamicDemo.RunDynamicWriteLine() in corewf\test\DynamicConsoleApp\DynamicConsoleApp.cs:line 43
   at DynamicConsoleApp.DynamicDemo.Main(String[] args) in corewf\test\DynamicConsoleApp\DynamicConsoleApp.cs:line 48

Update: A DynamicActivity without Properties (DynamicActivityProperty) works. 

Update2: Seems the error for the DynamicActivity properties is connected to the CacheMetadata. I can follow the track down to ExpressionUtilities from the Activity.InternalCacheMetadata.

Update3: [The fork has been updated with DynamicActivity inside](https://github.com/ewinnington/corewf/tree/49738f0eddaa6ef541e82adb3297bfd1343b705c).

**Comment by ewinnington** [comment]
[DynamicActivity declared in Imperative code works.](https://github.com/ewinnington/corewf)

That's enough for tonight. Tomorrow, I'll attack XAML Loading.

**Comment by dmetzgar** [comment]
Great work!
